root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "lsof -ti tcp:8080 | xargs kill -9 || true & go run main.go"
  exclude_dir = []
  exclude_file = ["seed.go"]
  exclude_regex = ["_test.go"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  log = "build-errors.log"